//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmasters
{
    using System;
    using System.Collections.Generic;
    
    public partial class registros
    {
        public int IdRegistro { get; set; }
        public System.DateTime Fecha_inscripcion { get; set; }
        public System.DateTime Fecha_realizacion { get; set; }
        public int usuariosIdUsuarios { get; set; }
        public int tourIdTour { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual tour tour { get; set; }
    }
}
