//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMasters
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBDDContext : DbContext
    {
        public BBDDContext()
            : base("name=BBDDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> UsuariosSet { get; set; }
        public virtual DbSet<Registros> RegistrosSet { get; set; }
        public virtual DbSet<Tours> ToursSet { get; set; }
        public virtual DbSet<Ciudades> CiudadesSet { get; set; }
    }
}
