//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMasters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros
    {
        public int RegistroId { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public System.DateTime FechaRealizacion { get; set; }
        public int GuiaId { get; set; }
        public int UsuarioId { get; set; }
        public int TourId { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Tours Tour { get; set; }
    }
}
